# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'managed': True,
                'verbose_name': 'karta menu',
                'verbose_name_plural': 'karty menu',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CardItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='restaurant.Card')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Opis')),
                ('sort', models.IntegerField(blank=True, default=1, verbose_name='Kolejność sortowania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'managed': True,
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('image', models.ImageField(blank=True, upload_to='static/images/dishes', verbose_name='Zdjęcie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('prep_time', models.IntegerField(verbose_name='Czas przygotowania [min.]')),
                ('vege', models.BooleanField(default=True, verbose_name='Wegetariańskie')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Categories', verbose_name='Kategoria')),
            ],
            options={
                'managed': True,
                'verbose_name': 'danie',
                'verbose_name_plural': 'dania',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='carditems',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='restaurant.Dish'),
        ),
    ]
