# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20170210_2059'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='card',
            index_together=set([]),
        ),
    ]
