# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Categories'),
        ),
    ]
