# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_dish_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cat',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Categories'),
        ),
    ]
