# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20170211_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Categories'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('MIESO', 'Dania mięsne'), ('MAKA', 'Dania mączne'), ('ZUPA', 'Zupy'), ('NAPOJ', 'Napoje'), ('ALKOHOL', 'Alkohole'), ('DESER', 'Desery'), ('INNE', 'Inne')], default='INNE', max_length=50),
        ),
    ]
