# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20170211_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
    ]
