# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_dish_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='cat',
            new_name='category',
        ),
    ]
